# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with coverage
      run: coverage run -m app_teste

    - name: Result
      run: coverage report

    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        image: yudihino/image
        tags: 1
        dockerfile: dockerfile
        registry: docker.io
        username: ${{ secrets.USER_DOCKER }}
        # Docker registry password
        password: ${{ secrets.PASSWORD_DOCKER }}
