# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with coverage
      run: coverage run -m app_teste

    - name: Result
      run: coverage report

    - name: Deploy no EC2 - AWS
      run: |
        echo "Conectando no EC2"
        echo "${{secrets.AWS_PEM}}" > private_key && chmod 600 private_key 
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-18-204-100-152.compute-1.amazonaws.com "
            cd gitActionEx3/;git pull;./IniciarApp.sh"

    - name: Render Deploy Actions
      uses: johnbeynon/render-deploy-action@v0.0.8
      with: 
        service-id: srv-crr0rqjv2p9s73e96m1g
        api-key: rnd_Im5n9SOAN2yFmN1a2Cvs8c5VgSLz
